# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://www.jofun.win/ # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : jofun's blog
description: > # this means to ignore newlines until "Language & timezone"
  jofun's blog


## => Language and Timezone
##############################
lang: zh # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : jofunLiang
  url       :
  avatar    : https://avatars0.githubusercontent.com/u/26024762?s=40&v=4 # path or url of avatar image
  bio       : I am an amazing person.
  email     : # lianghaozhuo@yeah.net
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name/
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name/
  github    : JofunLiang # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: jofunLiang/JofunLiang.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## license
license: # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 10
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Comments
##############################
comments:
  provider: "disqus" # false (default), "disqus", "gitalk", "custom"

  ## Disqus
  disqus:
    shortname: myBlog # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
  clientID: a68b6e804eda17d1a6c7 # GitHub Application Client ID
  clientSecret: 79c411546dc59b6f621caf9160e2f4f3042e54ec # GitHub Application Client Secret
  repository: JofunLiang.github.io # GitHub repo
  owner: jofunLiang # GitHub repo owner
  admin: # Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - jofunLiang


## => Pageview
##############################
pageview:
  provider: 'leancloud' # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : 4LBlpULyr5OjUALfUvjtukt2-gzGzoHsz
    app_key   : 7wnFuSD0E39BHNYHBH9OWBgp
    app_class : my_blog


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
